
build: install.iso docker-wine

install.iso:
	curl -o install.iso -L https://archive.org/download/lotus-smart-suite-9.8.2-millennium-edition-9.8.2-2009-03-english-cd/Lotus%20SmartSuite.iso

docker-wine:
	curl -o docker-wine https://raw.githubusercontent.com/scottyhardy/docker-wine/master/docker-wine
	chmod +x docker-wine

